package handlers

import (
	_ "WebServer/cmd/webserver/docs" // docs is generated by Swag CLI, you have to import it.
	"WebServer/cmd/webserver/models"
	"net/http"

	"github.com/gin-gonic/gin"
	// swagger embed files
)

// ChangeClientCard godoc
// @Summary Сохраняет данные по делам в биллинговой системе
// @Description Передача данных по делам из Jeffit во внешнюю систему
// @Accept  json
// @Produce json
// Param [param_name] [param_type] [data_type] [required/mandatory] [description]
// @Param q body models.TDelo false "name search by q"
// @Success 200 {object} models.TData_resp
// @Router /changeclientcard/ [post]
func ChangeClientCard(c *gin.Context) {

	var json models.TDelo
	var resp models.TData_resp
	if err := c.ShouldBindJSON(&json); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	/*	if json.User == "test" {
			logs.WithFields(logs.Fields{
				"Status": 0,
			}).Info("Ok")
			resp.Status = 0
			c.JSON(http.StatusOK, resp)
		} else {
			logs.WithFields(logs.Fields{
				"User": json.User,
			}).Info("Ok")
			resp.Status = 0

		}*/
	c.JSON(http.StatusOK, resp)
}
