package handlers

import (
	_ "WebServer/cmd/webserver/docs" // docs is generated by Swag CLI, you have to import it.
	"WebServer/cmd/webserver/models"
	"WebServer/version"
	"net/http"

	"github.com/gin-gonic/gin"
	// swagger embed files
)

// HomeHandlers godoc
// @Summary Retrieves user based on given ID
// @Produce json
// @Success 200 {object} models.Version
// @Router /home/ [post]
func HomeHandlers(c *gin.Context) {
	var vers models.Version
	vers.BuildTime = version.BuildTime
	vers.Commit = version.Commit
	vers.Release = version.Release
	c.JSON(http.StatusOK, vers)

}
