package main

import (
	routes "WebServer/cmd/webserver/routes"
	"WebServer/version"

	//	_ "test/docs" // docs is generated by Swag CLI, you have to import it.
	gin "github.com/gin-gonic/gin"
	logs "github.com/sirupsen/logrus"
)

var router *gin.Engine

func setupRouter() *gin.Engine {
	logs.SetFormatter(&logs.JSONFormatter{})

	logs.WithFields(logs.Fields{
		"commit":     version.Commit,
		"build time": version.BuildTime,
		"release":    version.Release,
	}).Info("Starting the service...")

	router := gin.Default()

	//router.LoadHTMLGlob("templates/*")

	routes.InitializeRoutes(router)

	return router
}

// @title Swagger IRBiS API.
// @version 1.0
// @description wbfywefqybfeyuf
// @termsOfService

// @contact.name API Support
// @contact.url http://servicedesk.tattelecom.ttc
// @contact.email servicedesk@tattelecom.ru

// @host localhost:5000
// @BasePath /billing/api/v1
func main() {
	router := setupRouter()
	router.Run(":5000")
}
